name: env_ml
channels:
  - pytorch-lts
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _pytorch_select=0.1
  - absl-py=1.0.0
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - argcomplete=1.12.3
  - argon2-cffi=21.1.0
  - astroid=2.9.0
  - async-timeout=4.0.2
  - async_generator=1.10
  - asynctest=0.13.0
  - attrs=21.2.0
  - autopep8=1.6.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - blas=1.0
  - bleach=4.1.0
  - blinker=1.4
  - blosc=1.21.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.18.1
  - c-blosc2=2.0.4
  - ca-certificates=2021.10.8
  - cachetools=4.2.4
  - certifi=2021.10.8
  - cffi=1.15.0
  - cfitsio=4.0.0
  - chardet=4.0.0
  - charls=2.2.0
  - charset-normalizer=2.0.9
  - click=8.0.3
  - cloudpickle=2.0.0
  - colorama=0.4.4
  - cpuonly=1.0
  - cryptography=36.0.0
  - cycler=0.11.0
  - cytoolz=0.11.2
  - dask-core=2021.12.0
  - dataclasses=0.8
  - debugpy=1.5.1
  - decorator=5.1.0
  - defusedxml=0.7.1
  - docopt=0.6.2
  - entrypoints=0.3
  - fonttools=4.28.5
  - freetype=2.10.4
  - frozenlist=1.2.0
  - fsspec=2021.11.1
  - giflib=5.2.1
  - google-auth=1.35.0
  - google-auth-oauthlib=0.4.1
  - grpcio=1.43.0
  - idna=2.9
  - imagecodecs=2021.11.20
  - imageio=2.6.1
  - importlib-metadata=4.10.0
  - importlib_metadata=4.10.0
  - importlib_resources=5.4.0
  - intel-openmp=2019.4
  - ipykernel=6.6.0
  - ipython=7.30.1
  - ipython_genutils=0.2.0
  - isort=5.10.1
  - jbig=2.1
  - jedi=0.18.1
  - jinja2=3.0.3
  - joblib=1.1.0
  - jpeg=9d
  - jsonschema=4.3.2
  - jupyter_client=7.1.0
  - jupyter_core=4.9.1
  - jupyterlab_pygments=0.1.2
  - jxrlib=1.1
  - kiwisolver=1.3.2
  - krb5=1.19.2
  - lazy-object-proxy=1.7.1
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=3.0
  - libaec=1.0.6
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=7.80.0
  - libdeflate=1.8
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - liblapack=3.9.0
  - libmklml=2019.0.5
  - libnghttp2=1.43.0
  - libnsl=2.0.0
  - libopenblas=0.3.18
  - libpng=1.6.37
  - libprotobuf=3.19.1
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.3.0
  - libwebp-base=1.2.1
  - libzlib=1.2.11
  - libzopfli=1.0.3
  - locket=0.2.0
  - lz4-c=1.9.3
  - markdown=3.3.6
  - markupsafe=2.0.1
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.3
  - mccabe=0.6.1
  - mistune=0.8.4
  - mkl=2020.2
  - multidict=5.2.0
  - munkres=1.1.4
  - nbclient=0.5.9
  - nbconvert=6.3.0
  - nbformat=5.1.3
  - ncurses=6.2
  - nest-asyncio=1.5.4
  - networkx=2.6.3
  - ninja=1.10.2
  - notebook=6.4.6
  - numpy=1.21.5
  - oauthlib=3.1.1
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=3.0.0
  - packaging=21.3
  - pandas=1.3.5
  - pandoc=2.16.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - partd=1.2.0
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.2.0
  - pip=21.3.1
  - pipreqs=0.4.10
  - platformdirs=2.3.0
  - prometheus_client=0.12.0
  - prompt-toolkit=3.0.24
  - protobuf=3.19.1
  - ptyprocess=0.7.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycodestyle=2.8.0
  - pycparser=2.21
  - pygments=2.10.0
  - pyjwt=2.3.0
  - pylint=2.12.2
  - pyopenssl=21.0.0
  - pyparsing=3.0.6
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.7.12
  - python-dateutil=2.8.2
  - python_abi=3.7
  - pytorch=1.8.1
  - pytz=2021.3
  - pyu2f=0.1.5
  - pywavelets=1.2.0
  - pyyaml=6.0
  - pyzmq=22.3.0
  - readline=8.1
  - requests=2.26.0
  - requests-oauthlib=1.3.0
  - rsa=4.8
  - scikit-image=0.19.1
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - send2trash=1.8.0
  - setuptools=60.1.0
  - six=1.16.0
  - snappy=1.1.8
  - sqlite=3.37.0
  - tensorboard=2.4.1
  - tensorboard-plugin-wit=1.8.0
  - terminado=0.12.1
  - testpath=0.5.0
  - threadpoolctl=3.0.0
  - tifffile=2021.11.2
  - tk=8.6.11
  - toml=0.10.2
  - toolz=0.11.2
  - torchaudio=0.8.1
  - torchvision=0.9.1
  - tornado=6.1
  - tqdm=4.62.3
  - traitlets=5.1.1
  - typed-ast=1.5.1
  - typing-extensions=4.0.1
  - typing_extensions=4.0.1
  - unicodedata2=14.0.0
  - urllib3=1.26.7
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=2.0.1
  - wheel=0.37.1
  - wrapt=1.13.3
  - xz=5.2.5
  - yaml=0.2.5
  - yarg=0.1.9
  - yarl=1.7.2
  - zeromq=4.3.4
  - zfp=0.5.5
  - zipp=3.6.0
  - zlib=1.2.11
  - zstd=1.5.0
